[package]
name = "dual_number"
version = "0.1.0"
edition = "2024"

[dependencies]
linear_algebra = {path = "/home/oliver/sd/programming/rust/utilities/linear_algebra"}
quaternion = {path = "../quaternion"}