unstable_features = true
condense_wildcard_suffixes = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
style_edition = "2024"
wrap_comments = true